#!/bin/bash

# TwinMind Deployment Starter
# This will open deployment interfaces and show you exactly what to do

echo "🚀 TwinMind Deployment"
echo "======================"
echo ""
echo "I'll open the deployment websites for you."
echo "Follow the simple steps below!"
echo ""

# Qdrant credentials (already have)
QDRANT_URL="https://d4c85a4b-2f42-44e4-8b39-8b94aa574108.europe-west3-0.gcp.cloud.qdrant.io:6333"
QDRANT_API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.JGH3PuWGGP8p2wDuRfZz9fz9mOuBTN7AIN2xHC1GAWk"

echo "✅ Qdrant credentials ready!"
echo ""
echo "📋 Your Qdrant Details:"
echo "   URL: $QDRANT_URL"
echo "   API Key: $QDRANT_API_KEY"
echo ""

read -p "Press Enter to open Railway (Backend deployment)..."

# Open Railway
open "https://railway.app/new" 2>/dev/null || xdg-open "https://railway.app/new" 2>/dev/null || echo "Please visit: https://railway.app/new"

echo ""
echo "=========================================="
echo "  STEP 1: RAILWAY (Backend)"
echo "=========================================="
echo ""
echo "1. Click 'Deploy from GitHub repo'"
echo "2. Select 'TwinMind' repository"
echo "3. Railway will detect your Dockerfile"
echo ""
echo "4. Add PostgreSQL:"
echo "   • Click '+ New' → 'Database' → 'PostgreSQL'"
echo ""
echo "5. Add Redis:"
echo "   • Click '+ New' → 'Database' → 'Redis'"
echo ""
echo "6. Configure Backend Service:"
echo "   • Root Directory: backend"
echo "   • Build: (auto-detected)"
echo "   • Start: uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "7. Add Environment Variables (in Variables tab):"
echo ""
echo "   QDRANT_URL=$QDRANT_URL"
echo "   QDRANT_API_KEY=$QDRANT_API_KEY"
echo "   OPENAI_API_KEY=<your-openai-key>"
echo "   STORAGE_TYPE=local"
echo "   ENVIRONMENT=production"
echo "   ALLOWED_ORIGINS=https://your-frontend.vercel.app"
echo "   SECRET_KEY=<generate-random-32-char-string>"
echo ""
echo "   Note: DATABASE_URL and REDIS_URL are auto-added by Railway!"
echo ""
read -p "Press Enter when Railway deployment is started..."

echo ""
echo "=========================================="
echo "  STEP 2: VERCEL (Frontend)"
echo "=========================================="
echo ""

read -p "Press Enter to open Vercel..."

open "https://vercel.com/new" 2>/dev/null || xdg-open "https://vercel.com/new" 2>/dev/null || echo "Please visit: https://vercel.com/new"

echo ""
echo "1. Click 'Import' your GitHub repository"
echo "2. Select 'TwinMind' repository"
echo ""
echo "3. Configure:"
echo "   • Framework: Next.js (auto-detected)"
echo "   • Root Directory: frontend"
echo "   • Build Command: npm run build"
echo ""
echo "4. Add Environment Variable:"
echo "   • Name: NEXT_PUBLIC_API_URL"
echo "   • Value: <your-railway-backend-url>"
echo "     (Get this from Railway dashboard after deployment)"
echo ""
echo "5. Click 'Deploy'"
echo ""
echo "=========================================="
echo ""
echo "✅ After both are deployed:"
echo "   1. Copy your Vercel frontend URL"
echo "   2. Update ALLOWED_ORIGINS in Railway with Vercel URL"
echo "   3. Test your app!"
echo ""
echo "Your app will be live at your Vercel URL! 🎉"

